package com.laborun.entity;
// Generated Mar 19, 2015 10:40:45 PM by Hibernate Tools 4.3.1



/**
 * Admin generated by hbm2java
 */
public class Admin extends User implements java.io.Serializable {


     private int id;

    public Admin() {
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


}


