package com.laborun.entity;
// Generated Mar 21, 2015 3:25:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AssignmentFiles generated by hbm2java
 */
public class AssignmentFiles  implements java.io.Serializable {


     private int id;
     private Lab lab;
     private Trainee trainee;
     private byte[] uploadFile;
     private Date uploadDate;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    private String name;

    public AssignmentFiles() {
    }

	
    public AssignmentFiles(int id) {
        this.id = id;
    }
    public AssignmentFiles(int id, Lab lab, Trainee trainee, byte[] uploadFile, Date uploadDate) {
       this.id = id;
       this.lab = lab;
       this.trainee = trainee;
       this.uploadFile = uploadFile;
       this.uploadDate = uploadDate;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Lab getLab() {
        return this.lab;
    }
    
    public void setLab(Lab lab) {
        this.lab = lab;
    }
    public Trainee getTrainee() {
        return this.trainee;
    }
    
    public void setTrainee(Trainee trainee) {
        this.trainee = trainee;
    }
    public byte[] getUploadFile() {
        return this.uploadFile;
    }
    
    public void setUploadFile(byte[] uploadFile) {
        this.uploadFile = uploadFile;
    }
    public Date getUploadDate() {
        return this.uploadDate;
    }
    
    public void setUploadDate(Date uploadDate) {
        this.uploadDate = uploadDate;
    }




}


