package com.laborun.entity;
// Generated Mar 21, 2015 3:25:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Department generated by hbm2java
 */
public class Department  implements java.io.Serializable {


     private Integer id;
     private String departmentName;
     private Set userDs = new HashSet(0);
     private Set courses = new HashSet(0);

    public Department() {
    }

    public Department(String departmentName, Set userDs, Set courses) {
       this.departmentName = departmentName;
       this.userDs = userDs;
       this.courses = courses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDepartmentName() {
        return this.departmentName;
    }
    
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }
    public Set getUserDs() {
        return this.userDs;
    }
    
    public void setUserDs(Set userDs) {
        this.userDs = userDs;
    }
    public Set getCourses() {
        return this.courses;
    }
    
    public void setCourses(Set courses) {
        this.courses = courses;
    }




}


