package com.laborun.entity;
// Generated Mar 19, 2015 10:40:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Group generated by hbm2java
 */
public class Group  implements java.io.Serializable {


     private int id;
     private String groupName;
     private Set users = new HashSet(0);
     private Set courses = new HashSet(0);
     private Intake intake;

    public Intake getIntake() {
        return intake;
    }

    public void setIntake(Intake intake) {
        this.intake = intake;
    }
     
    public Group() {
    }

	
    public Group(int id, String groupName) {
        this.id = id;
        this.groupName = groupName;
    }
    public Group(int id, String groupName, Set users, Set courses) {
       this.id = id;
       this.groupName = groupName;
       this.users = users;
       this.courses = courses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }
    public Set getCourses() {
        return this.courses;
    }
    
    public void setCourses(Set courses) {
        this.courses = courses;
    }




}


