package com.laborun.entity;
// Generated Mar 21, 2015 3:25:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * GroupD generated by hbm2java
 */
public class GroupD  implements java.io.Serializable {


     private int id;
     private Intake intake;
     private String groupName;
     private Set userDs = new HashSet(0);
     private Set courses = new HashSet(0);

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public GroupD() {
    }

	
    public GroupD(Intake intake, String groupName) {
      
        this.intake = intake;
        this.groupName = groupName;
    }
    public GroupD( Intake intake, String groupName, Set userDs, Set courses) {
      
       this.intake = intake;
       this.groupName = groupName;
       this.userDs = userDs;
       this.courses = courses;
    }
   
   
    public Intake getIntake() {
        return this.intake;
    }
    
    public void setIntake(Intake intake) {
        this.intake = intake;
    }
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }
    public Set getUserDs() {
        return this.userDs;
    }
    
    public void setUserDs(Set userDs) {
        this.userDs = userDs;
    }
    public Set getCourses() {
        return this.courses;
    }
    
    public void setCourses(Set courses) {
        this.courses = courses;
    }




}


