package com.laborun.entity;
// Generated Mar 19, 2015 10:40:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Intake generated by hbm2java
 */
public class Intake  implements java.io.Serializable {


     private int id;
     private int intakeNum;
     private Set trainees = new HashSet(0);
     private Set Groups = new HashSet();

    public Set getGroups() {
        return Groups;
    }

    public void setGroups(Set Groups) {
        this.Groups = Groups;
    }
     
    public Intake() {
    }

	
    public Intake(int id, int intakeNum) {
        this.id = id;
        this.intakeNum = intakeNum;
    }
    public Intake(int id, int intakeNum, Set trainees) {
       this.id = id;
       this.intakeNum = intakeNum;
       this.trainees = trainees;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getIntakeNum() {
        return this.intakeNum;
    }
    
    public void setIntakeNum(int intakeNum) {
        this.intakeNum = intakeNum;
    }
    public Set getTrainees() {
        return this.trainees;
    }
    
    public void setTrainees(Set trainees) {
        this.trainees = trainees;
    }




}


