package com.laborun.entity;
// Generated Mar 21, 2015 3:25:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Intake generated by hbm2java
 */
public class Intake  implements java.io.Serializable {


     private Integer id;
     private int intakeNum;
     private Set groupDs = new HashSet(0);
     private Set trainees = new HashSet(0);

    public Intake() {
    }

	
    public Intake(int intakeNum) {
        this.intakeNum = intakeNum;
    }
    public Intake(int intakeNum, Set groupDs, Set trainees) {
       this.intakeNum = intakeNum;
       this.groupDs = groupDs;
       this.trainees = trainees;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getIntakeNum() {
        return this.intakeNum;
    }
    
    public void setIntakeNum(int intakeNum) {
        this.intakeNum = intakeNum;
    }
    public Set getGroupDs() {
        return this.groupDs;
    }
    
    public void setGroupDs(Set groupDs) {
        this.groupDs = groupDs;
    }
    public Set getTrainees() {
        return this.trainees;
    }
    
    public void setTrainees(Set trainees) {
        this.trainees = trainees;
    }




}


