package com.laborun.entity;
// Generated Mar 19, 2015 10:40:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Queue generated by hbm2java
 */
public class Queue  implements java.io.Serializable {


     private int id;
     private Lab lab;
     private String queueType;
     private Set traineeInQueues = new HashSet(0);

    public Queue() {
    }

	
    public Queue(int id) {
        this.id = id;
    }
    public Queue(int id, Lab lab, String queueType, Set traineeInQueues) {
       this.id = id;
       this.lab = lab;
       this.queueType = queueType;
       this.traineeInQueues = traineeInQueues;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Lab getLab() {
        return this.lab;
    }
    
    public void setLab(Lab lab) {
        this.lab = lab;
    }
    public String getQueueType() {
        return this.queueType;
    }
    
    public void setQueueType(String queueType) {
        this.queueType = queueType;
    }
    public Set getTraineeInQueues() {
        return this.traineeInQueues;
    }
    
    public void setTraineeInQueues(Set traineeInQueues) {
        this.traineeInQueues = traineeInQueues;
    }




}


