package com.laborun.entity;
// Generated Mar 19, 2015 10:40:45 PM by Hibernate Tools 4.3.1



/**
 * TraineeInQueue generated by hbm2java
 */
public class TraineeInQueue  implements java.io.Serializable {


     private TraineeInQueueId id;
     private Queue queue;
     private Trainee trainee;
     private int order;

    public TraineeInQueue() {
    }

    public TraineeInQueue(TraineeInQueueId id, Queue queue, Trainee trainee, int order) {
       this.id = id;
       this.queue = queue;
       this.trainee = trainee;
       this.order = order;
    }
   
    public TraineeInQueueId getId() {
        return this.id;
    }
    
    public void setId(TraineeInQueueId id) {
        this.id = id;
    }
    public Queue getQueue() {
        return this.queue;
    }
    
    public void setQueue(Queue queue) {
        this.queue = queue;
    }
    public Trainee getTrainee() {
        return this.trainee;
    }
    
    public void setTrainee(Trainee trainee) {
        this.trainee = trainee;
    }
    public int getOrder() {
        return this.order;
    }
    
    public void setOrder(int order) {
        this.order = order;
    }




}


