package com.laborun.entity;
// Generated Mar 21, 2015 3:25:42 PM by Hibernate Tools 4.3.1



/**
 * TraineeInQueueId generated by hbm2java
 */
public class TraineeInQueueId  implements java.io.Serializable {


     private int traineeId;
     private int queueId;

    public TraineeInQueueId() {
    }

    public TraineeInQueueId(int traineeId, int queueId) {
       this.traineeId = traineeId;
       this.queueId = queueId;
    }
   
    public int getTraineeId() {
        return this.traineeId;
    }
    
    public void setTraineeId(int traineeId) {
        this.traineeId = traineeId;
    }
    public int getQueueId() {
        return this.queueId;
    }
    
    public void setQueueId(int queueId) {
        this.queueId = queueId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TraineeInQueueId) ) return false;
		 TraineeInQueueId castOther = ( TraineeInQueueId ) other; 
         
		 return (this.getTraineeId()==castOther.getTraineeId())
 && (this.getQueueId()==castOther.getQueueId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getTraineeId();
         result = 37 * result + this.getQueueId();
         return result;
   }   


}


